### ISSUE TITLE
Grind Tray Closes on First Run

### ISSUE THREAD

**Issue by sco-owe** [Arjailer/Bugs#36]
**Describe the bug**
Whenever I use the hotkey to search, Grind tray closes/crashes.

**Reproduction steps**
1. Start Grind Tray
2. Hotkey search selected (Win-F3 for me)
3. Nothing happens
4. Check the sys tray
5. Hover over Grind icon
6. Icon is removed

**Expected behavior**
Grind to start-up and populate search box with selected text

**Screenshots**
[GrindTray.webm](https://user-images.githubusercontent.com/34138055/211661816-81da9e7f-a4aa-4491-a73f-4e7b21ac1807.webm)

**Version information (please complete the following information):**
 - Application version: 1.34
 - Windows version: Windows 11

**Comment by Arjailer** [comment]
@sco-owe 

I've not been able to replicate this on Windows 10

Does it happen with the search **clipboard** hotkey, or does it only happen with search **selected**?
(trying to narrow down what code to look at)

I do have a Windows 11 PC and I'll try that later

**Comment by sco-owe** [comment]
Only the selected text, works when using the clipboard hotkey.

**Comment by Arjailer** [comment]
Replicated on Windows 11  👍

I'll dig in and see what's going wrong

**Comment by Arjailer** [comment]
@sco-owe 

I've got a work around - I'll put out a release in the next day or two  👍

**Comment by Arjailer** [comment]
v1.35 release should now be available with this fix
